### ISSUE TITLE
Use with Rack?

### ISSUE THREAD

**Issue by baelter** [sass/sassc-ruby#103]
How to replace

```ruby
require 'sass'
require 'sass/plugin/rack'

Sass::Plugin.options.merge! css_location: 'public/css', template_location: 'public/scss',
                            debug_info: true, style: :compressed
use Sass::Plugin::Rack
```

**Comment by mig-hub** [comment]
I was about to post the exact same question. I use the rack plugin and since I want to switch to sassc-ruby because of the deprecation of ruby-sass I too would like top know if there is an equivalent or an external gem which does this.

**Comment by mig-hub** [comment]
Clearly a very very naïve implementation, but you can use this in the meantime:

```ruby
require 'sassc'

class Rack::Sassc

  def initialize app
    @app = app
    @public_location = File.expand_path '../public', __FILE__
  end

  def call env
    process_file(env['PATH_INFO']) if ENV['RACK_ENV']=='development'
    @app.call env
  end

  private

  def process_file path_info
    if path_info[/\.css$/]
      filename = File.basename path_info, '.*'
      scss_filepath = filepath(filename, :scss)
      if File.exist?(scss_filepath)
        scss = File.read(scss_filepath)
        engine = SassC::Engine.new(scss, {
          style: :compressed, 
          load_paths: [location(:scss)],
          source_map_file: ".",
          source_map_embed: true,
          source_map_contents: true,
        })
        css_filepath = filepath(filename, :css)
        File.open(css_filepath, 'w') do |css_file|
          css_file.write(engine.render)
        end
      end
    end
  end

  def location ext
    File.join @public_location, ext.to_s
  end

  def filepath filename, ext
    File.join location(ext), "#{filename}.#{ext}"
  end

end

use Rack::Sassc
```

It assumes that the scss files are not nested but it should be easy to change. Partial imports are working if they are also in `#scss_location` not nested. And it basically reprocess the scss file each time the corresponding css file is requested when in development environment. Like I said naïve implementation but it is fairly quick on my machine.

The most annoying thing is that I could not make it create the source map file I wanted. I tried but could not get it to do exactly what I wanted. Partly because I don't know the gem enough yet and it is not easy to find documentation for options with examples. And the tests tells me only how to do it with the contents. But if you are interested, the gist of it is that there are a few other options for the engine, like `source_map_file` and `source_map_contents`, and when you have these set, the engine `#source_map` returns the string which you can save on a file like the actual css.

The problem is that whatever I do, I end up with "stdin" in there and incorrect paths, either full paths, request path_info, sometimes both. 

In the meantime, the version I've copied here has the source_map inlined. Which works fine but makes the file way bigger.

**Comment by bolandrm** [comment]
I would prefer to see this as an external gem.  If someone wanted to create it, I would be happy to link to it in the description.

**Comment by mig-hub** [comment]
Here is an updated version of the middleware which saves the map file separately (but still with contents included in it). Which makes it usable when debugging AND does not make your CSS file bigger.

```ruby
class Rack::Sassc

  def initialize app
    @app = app
    @public_location = File.expand_path '../public', __FILE__
  end

  def call env
    process_file(env['PATH_INFO']) if ENV['RACK_ENV']=='development'
    @app.call env
  end

  private

  def process_file path_info
    if path_info[/\.css$/]
      filename = File.basename path_info, '.*'
      scss_filepath = filepath(filename, :scss)
      if File.exist?(scss_filepath)
        scss = File.read(scss_filepath)
        engine = SassC::Engine.new(scss, {
          style: :compressed, 
          load_paths: [location(:scss)],
          source_map_file: "#{filename}.css.map",
          source_map_contents: true,
        })
        css_filepath = filepath(filename, :css)
        File.open(css_filepath, 'w') do |css_file|
          css_file.write(engine.render)
        end
        File.open("#{css_filepath}.map", 'w:ASCII-8BIT') do |map_file|
          map_file.write(engine.source_map)
        end
      end
    end
  end

  def location ext
    File.join @public_location, ext.to_s
  end

  def filepath filename, ext
    File.join location(ext), "#{filename}.#{ext}"
  end

end
```

**Comment by mig-hub** [comment]
@bolandrm yes me too but like I said it is a naïve approach which has no tests and assumes a limited scenario. Pretty much the way I use it. I would be happy to start a Gem with this but I thought it would pollute the Sassc/Rack namespace if somebody comes up with a more configurable Gem.

Nevertheless, please leave me messages here if people are interested, then I'll create a Gem. I'd be more than happy to do so. I can tweak it so that the engine options and directories for css and scss are accessible from the Gem's options.

**Comment by mig-hub** [comment]
@bolandrm , @baelter , Okay so I worked a bit more on it and created a small Gem: [Rack-SassC](https://github.com/mig-hub/rack-sassc)

I have also pushed a version `0.0.0` on rubygems, so you can install it with Bundler, or directly with Gem.

Please feel free to send me comments.

I actually found an alternative called [SasscRack](https://github.com/hkrutzer/sasscrack) by @hkrutzer. Arguably a much better name than mine `;-)`
