### ISSUE TITLE
SassC fails after upgrading to Tailwind 3

### ISSUE THREAD

**Issue by thomasvanholder** [sass/sassc-ruby#230]
After upgrading a Rails 6.1.4.1 app to the [TailwindCSS 3](https://github.com/tailwindlabs/tailwindcss), the following SassC error pops up. The odd behaviour is that this error only occurs in Github Actions, while locally everything works as inteded.

```bash
Failure/Error: Unable to find stdin to read failed line

ActionView::Template::Error:
  Error: Function rgb is missing argument $green.
          on line 436 of stdin
  >>   border-color: rgb(229 231 235 / var(--tw-border-opacity));

    ----------------^
# stdin:436
# ------------------
# --- Caused by: ---
# SassC::SyntaxError:
#   Error: Function rgb is missing argument $green.
#           on line 436 of stdin
#   >>   border-color: rgb(229 231 235 / var(--tw-border-opacity));
#   
#      ----------------^
#   stdin:436
```

Any ideas?

**Comment by ggsp** [comment]
I think I'm seeing something similar on my Rails app—everything works fine locally, but things break on CI.

In my case, the issue is with the `hsla()` function instead of `rgb()`, but it should be equivalent because I also have a CSS variable in a color function, which seems to be what LibSass is ultimately hiccuping on. I am currently trying to add an administration gem which depends on SassC, so the error is popping up for the first time.

When precompiling locally, I see no errors: Webpacker takes care of it. If instead I run `RAILS_ENV=production bundle exec rake assets:precompile`, I see an error equivalent to yours. 

My understanding is that because I am using Webpacker in development, things ultimately rely on DartSass, which can deal with a CSS variable inside of a SASS function. SassC instead relies on LibSass, which is deprecated and thus never added [and never will add](https://github.com/sass/sass/issues/2564#issuecomment-716888385) support for this functionality.

Unfortunately, I've yet to find a solution—besides not using the gem which relies on SassC, which is a pretty undesirable solution.

**Comment by ggsp** [comment]
I think I'm seeing something similar in my Rails app—everything works fine locally, but things break on CI. This is the output of `RAILS_ENV=production bundle exec rake assets:precompile`:

```
SassC::SyntaxError: Error: Function hsla is missing argument $lightness.
        on line 57 of stdin
>>   background: hsla(var(--primary-color), 1);

   --------------^
```

This error should be equivalent to yours as I also have a CSS custom property in a color function, which seems to be what LibSass is ultimately hiccuping on. For context, I am currently trying to add an administration gem which depends on SassC; this error is popping up for the first time because of that.

My understanding is that because I am using Webpacker in development, precompilation works without issue. Webpacker [relies on DartSass](https://github.com/rails/webpacker/pull/2716), which can deal with a CSS custom property inside of a color function.

SassC instead relies on LibSass, which seemingly [also implemented this functionality](https://github.com/sass/libsass/issues/2244). The trail currently goes cold for me here. Maybe LibSass interprets the above as a SASS color function, while DartSass sees it as a CSS color function? Nothing but a vague guess on my part.

I've yet to find a solution—besides not using the gem which relies on SassC, which is not the most desirable.

**Comment by thomasvanholder** [comment]
@ggsp, I ended up switching to PostCSS which can mimick sass behaviour.
