### ISSUE TITLE
SassC::Engine#render attempts to mutate frozen strings

### ISSUE THREAD

**Issue by searls** [sass/sassc-ruby#82]
Frozen strings being all the rage right now, I just wanted to note that passing a frozen string to an engine and calling render will raise a `FrozenError`.

Here's an irb demo:

```ruby
> require "sassc"
true
> SassC::Engine.new("body {}".freeze).render
Traceback (most recent call last):
        5: from /Users/justin/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        4: from (irb):5
        3: from /Users/justin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sassc-1.12.1/lib/sassc/engine.rb:22:in `render'
        2: from /Users/justin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sassc-1.12.1/lib/sassc/native/native_context_api.rb:16:in `make_data_context'
        1: from /Users/justin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sassc-1.12.1/lib/sassc/native.rb:52:in `native_string'
FrozenError (can't modify frozen String)
```

**Comment by bolandrm** [comment]
Thanks for the report @searls !  This seems to have been fixed with our 2.0.0 release.   For good measure, i've added a test:  https://github.com/sass/sassc-ruby/commit/c2d6de791ba3eb328c30f6a61fd9ac37791bae75

Going to close, but let me know if you are still running into this issue and i'll reopen.
